const collectionsIndexerParameters: string[] = [
  "Degenerate Ape Academy",
  "Exiled Degen Ape Academy",
  "Solarians",
  "Abstratica",
  "Boogle",
  "Cyber Samurai",
  "SolanaDogeNFTs",
  "Solpops",
  "Solstones",
  "Top Hat Chicks",
  "Rox",
  "Frakt",
  "NoGoalFaces",
  "Solana Monkey Business",
  "Solana Monkey Business OG",
  "Thugbirdz",
  "Kaiju Cards",
  "RAM NFT",
  "SolChihuahua NFT",
  "Soliens",
  "Kreechures",
  "Pixel Penguins",
  "Solana Beach Surf Shop",
  "SolFood",
  "Toposcapes",
  "Turtle Traders NFT",
  "SolGangsta",
  "Solanimals",
  "Solana Mecha War",
  "Mercurial Finance",
  "Solana Puppy",
  "Soldalas",
  "Solshrooms",
  "Gym Rats",
  "el topo",
  "ApeShit Social Club",
  "Solana Mees",
  "SolSkull",
  "SolBear",
  "MetaMorph",
  "SOLLOWEEN",
  "Pixel POO",
  "Solamask",
  "BasketNFT",
  "SolRanNFT",
  "RNFTz",
  "Gnarly Gnomies",
  "Polyline",
  "Pigna the cat kaleidoscope cat",
  "Hemp",
  "Jamie Forbes Art",
  "Endangered Peruvian Wildlife",
  "Inksolum",
  "LIGHTS",
]

export default collectionsIndexerParameters;
