export const DIRECT_SELL_CONTRACT_ID = "7t8zVJtPCFAqog1DcnB6Ku1AVKtWfHkCiPi1cAvcJyVF";
export const DIRECT_SELL_TAX_ID = "3iYf9hHQPciwgJ1TCjpRUp1A3QW4AfaK7J6vCmETRMuu";
export const DIRECT_SELL_TAX_AMOUNT = "0.025";
